version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jayakanth
      POSTGRES_DB: Cyber
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:jayakanth@db:5432/Cyber
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    ports:
      - "3000:3000"

volumes:
  db_data:
