version: 1
build:
  commands:
    - cd backend
    - npm install
    - npm run build
services:
  - name: job-app-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    env: production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
databases:
  - name: job-app-db
    databaseName: jobapp
    user: jobapp